### ISSUE TITLE
Les images des Pokémons ne sont pas présentes

### ISSUE THREAD

**Issue by bastienvcnt** [chris-rousseau/shiny-hunt#1]
Bonjour,

J'ai remarqué que tu n'avais pas push le dossier "assets/img" et donc que les images des pokémons ne sont pas présentes. Est-ce volontaire ?

Autre question : quelles sont tes sources pour les données des Pokémons ? Je suis curieux de savoir au cas où un jour j'ai l'envie de faire une app.

**Comment by chris-rousseau** [comment]
Bonjour,

En effet il y a plus de 400 images, j'ai ajouté le dossier contenant les images dans mon .gitignore pour n'avoir que le code et non des images qui prennent de la place pour pas grand chose finalement.

Pour les données des Pokémon j'utilise seulement les noms, trouvable sur plusieurs sites spécialisés comme pokekalos.fr ou pokebip.com
Pour les illustrations elles ont été dataminées, j'ai trouvé un pack en cherchant un peu sur Twitter.
